### ISSUE TITLE
Display Pinned Notes

### ISSUE THREAD

**Issue by RushiDonga** [clubgamma/gamma_notes#1]
**1). Display Pinned Notes**
      To write the code for displaying the Pinned Notes, open the lib->Screens->pin_notes.dart file.

Hint!! Just need to add an if condition from the code in Home Page

**Comment by lalit-commits** [comment]
can I contribute?

**Comment by sneha-meto** [comment]
Hello, can you assign this to me?

**Comment by sneha-meto** [comment]
Hey, can you assign this to me?

**Comment by RushiDonga** [comment]
Yes, you can work on this Issue :)
