### ISSUE TITLE
Display Pin Icon in the card on the Home Page

### ISSUE THREAD

**Issue by RushiDonga** [clubgamma/gamma_notes#12]
Display a Green colour Pin Icon on the cards on the home Page **if the Note is Pinned.**

You can add the Pin Icon top-right side of the card or at the bottom-right side of the card, also if needed increase the height of the card.

Hint !! Have a look at code in the file lib->Screens->add_notes.dart. It contains the pin functionality !

**Comment by abby3010** [comment]
I would be happy to take upon this issue!
