### ISSUE TITLE
Display Favourite Notes

### ISSUE THREAD

**Issue by RushiDonga** [clubgamma/gamma_notes#2]
**2). Display Favourite Notes**
      To write the code for displaying the Favourite Notes, open the lib->Screens->fav_notes.dart file.
 
Hint!! Just need to an if condition from the code in Home Page

**Comment by Shash0501** [comment]
@RushiDonga I would like to work on this issue.

**Comment by RushiDonga** [comment]
Yes, you can work on this Issue..! :)
