### ISSUE TITLE
Copy Notes Feature

### ISSUE THREAD

**Issue by RushiDonga** [clubgamma/gamma_notes#4]
**4). Copy Notes Feature**
      To write your logic for Copying the notes, open the lib->Screens->add_notes.dart.
 
  <img src="https://user-images.githubusercontent.com/65907580/134803521-0283ea74-5c29-4ae8-b3a3-da6005289501.PNG" width="600" height="300" />

**Comment by Flamingloon** [comment]
Hey, I would like to work on this issue. Can you please assign it to me?
