### ISSUE TITLE
Send Notes Feature

### ISSUE THREAD

**Issue by RushiDonga** [clubgamma/gamma_notes#5]
**5). Send Notes Feature**
      To write your logic for Sending the notes, open the lib->Screens->add_notes.dart.
      
      Hint!: Can use **share:** package of Flutter
     
  <img src="https://user-images.githubusercontent.com/65907580/134803538-eff45d48-d1b0-4009-936d-76768eb84eed.PNG" width="600" height="300" />

**Comment by Flamingloon** [comment]
Hey, I would like to work on this issue. Can you please assign it to me?

**Comment by RushiDonga** [comment]
Yup..!, You can work on this Issue.

**Comment by RushiDonga** [comment]
Great work @Flamingloon
